'use client'
import { useState, useEffect, useRef } from 'react'

const CHAPTERS = [
  {
    id: 'foundation',
    number: '01',
    title: 'The Foundation',
    subtitle: 'Understanding the platform and your role',
    icon: '◈',
    color: '#a855f7',
    sections: [
      {
        title: 'What Texting Factory Actually Is',
        content: `Texting Factory is a platform where operators — real people — manage conversations on behalf of platform profiles. Men on the platform are paying for connection, attention, and the feeling of being genuinely wanted by someone. Your job is to provide that experience authentically and consistently.

You are not a bot. You are not a script. You are a woman having real conversations — curious, warm, occasionally playful, occasionally bold. The quality of that experience determines everything: tips, retention, and whether a man stays engaged for weeks or disappears after two messages.

The best operators understand this: men are not paying for words. They are paying for a feeling. Your replies create that feeling.`
      },
      {
        title: 'The Operator Mindset',
        content: `Think of yourself as an actress who has fully become the character. Not someone reading lines — someone living them. The woman you are playing has a personality, preferences, history, and genuine curiosity about the men she talks to.

Every conversation is an opportunity to create a genuine connection within the boundaries of the platform. That connection is what keeps men coming back, spending more, and tipping generously.

The operators who earn the most are not the ones who send the most messages. They are the ones whose messages feel the most real.`
      },
      {
        title: 'Platform Boundaries You Must Never Cross',
        content: `These are not suggestions — they are absolute rules that protect you, the platform, and the men on it:

Never arrange or agree to an in-person meeting. Ever. Not "maybe someday," not "when things are different." No meeting. Not under any circumstances.

Never share or request contact information. No phone numbers, no social media handles, no email addresses, no Snapchat, nothing that takes communication off the platform.

Never promise or imply that real-world contact is possible. This includes phrases like "I wish I could meet you" or "maybe one day." These create false expectations and violate platform terms.

Never share personal identifying information. Not your real name, your actual city, your workplace, your real appearance if it differs from the profile.

These rules exist because violating them puts everyone at risk. No exception is worth it.`
      }
    ]
  },
  {
    id: 'conversation',
    number: '02',
    title: 'The Art of Conversation',
    subtitle: 'How to build and sustain genuine engagement',
    icon: '◎',
    color: '#38bdf8',
    sections: [
      {
        title: 'The First Response Rule',
        content: `The first reply sets the entire tone of the conversation. It tells the man what kind of woman he is dealing with — interesting or boring, engaged or indifferent, worth pursuing or not.

A strong first reply does three things: it acknowledges what he said, it adds her perspective or reaction, and it ends with a pull that makes him want to respond immediately.

A weak first reply copies his words back, asks a generic question, or sounds like it was generated by a machine. Men can feel the difference. The best first reply makes him think "she actually read what I wrote."

Take his opening message and find the most interesting or specific thing in it. Build from that. Show you were paying attention.`
      },
      {
        title: 'Reading Between the Lines',
        content: `What a man writes is rarely the whole story. The best operators learn to read what is behind the words.

When a man says "I've been working a lot lately" — he is not reporting his schedule. He is probably telling you he is stressed, isolated, or looking for someone to notice him.

When a man sends an explicit message early — he may be testing the connection, or he may be lonely and using boldness to mask it.

When a man asks personal questions rapidly — he is interested and invested. Meet that energy.

When a man goes quiet after an active conversation — something shifted. Do not panic. The re-engage tools exist precisely for this.

Read the emotional content, not just the literal words. Respond to how he feels, not just what he said.`
      },
      {
        title: 'The Conversation Arc',
        content: `Every conversation should move. Not necessarily toward anything explicit — but forward. Conversations that stay flat get abandoned.

The arc looks like this: opening warmth → genuine curiosity → shared moment or revelation → deeper connection → desire to continue.

Depth comes from specificity. "What do you do for fun?" is flat. "You mentioned you love hiking — what is it about being outside that gets you?" is specific and shows you listened.

Every reply should either deepen what was just shared, introduce something new, or create curiosity about what comes next. Stagnant conversations die. Moving conversations keep men engaged for hours.`
      },
      {
        title: 'The Question Craft',
        content: `Questions are your most powerful tool. But most operators ask the wrong kind.

Closed questions kill momentum: "Do you like movies?" can be answered in one word and then what?

Open questions create possibility: "What is the kind of movie that you will watch alone on a bad day and it never fails to fix things?" That question reveals personality, creates intimacy, and guarantees a real answer.

The best questions feel natural — like something you would genuinely want to know. They grow from what he just said, not from a script. They make him feel like she was listening so carefully that the question could only have come from this specific conversation.

Never ask more than one question per reply. Pick the best one and ask only that.`
      }
    ]
  },
  {
    id: 'language',
    number: '03',
    title: 'Language & Voice',
    subtitle: 'Writing like a real woman, not a chatbot',
    icon: '◇',
    color: '#fbbf24',
    sections: [
      {
        title: 'The Natural Voice',
        content: `Real women do not text in complete, perfectly structured sentences. They use fragments. They trail off with ellipses. They use contractions constantly — I'm, don't, can't, I've, wouldn't, we're. They occasionally start sentences with "And" or "But."

The single biggest tell that a message was generated is perfect grammar and over-polished language. Real people make small imperfections. They write quickly. They sometimes punctuate with their mood.

Authenticity beats perfection every time.`
      },
      {
        title: 'Punctuation as Personality',
        content: `How you punctuate creates voice. Used well, it makes messages feel human and textured:

A period ends a thought with weight. "I noticed." feels different from "I noticed!" — one is quiet and certain, the other is eager.

An ellipsis (...) creates suspense or trailing thought. "I mean... there might be something to that" feels like she is thinking in real time.

One exclamation point maximum per reply, and only when genuinely surprised or delighted — not as a default cheerfulness.

No em dashes in texts. No semicolons. Those are essay punctuation, not text punctuation.

Short sentences land hard. A longer one that follows builds and flows into him.`
      },
      {
        title: 'Words That Kill Authenticity',
        content: `These phrases immediately signal that a message is not real. Avoid them without exception:

"That sounds amazing" — too performed. Real people say "okay that is actually incredible" or nothing at all.

"How sweet" — patronizing and generic. No woman under 60 texts this.

"I love that" — hollow affirmation. Say what specifically you love and why.

"Wow" alone — filler. Replace with something specific.

"Tell me more" — lazy. Ask a specific question instead.

"Be honest with me" — this is the most overused AI phrase in existence. Never use it.

"Okay your turn" — sounds like a game show host. Real conversations do not have turns announced.

Replace all of these with something specific to what he actually said.`
      },
      {
        title: 'Quoting vs Paraphrasing',
        content: `Quoting his exact words back in quotation marks sounds like a chatbot. Real people do not do this.

Wrong: "When you said 'I love hiking in the mountains' I thought that was really interesting."

Right: "The fact that you actually get out there and do it rather than just watching videos about it says something about you."

Paraphrase his ideas into your perspective. Absorb what he said and reflect it back through your own lens. That is how real people acknowledge each other — not by repeating, but by responding.`
      }
    ]
  },
  {
    id: 'advanced',
    number: '04',
    title: 'Advanced Techniques',
    subtitle: 'What separates good operators from great ones',
    icon: '◈',
    color: '#22c55e',
    sections: [
      {
        title: 'Managing Multiple Conversations',
        content: `When managing several conversations simultaneously, the temptation is to use the same replies or approach for everyone. Resist this completely.

Each man deserves to feel like the only one she is focused on. That means referencing specific things from their specific conversation, using his name occasionally, and building on what was previously established.

Keep a mental note (or written notes) of key details each man has shared — his job, his city, what he cares about, what made him laugh. Use those details to make future messages feel impossibly personal.

The man who feels like she actually remembers him will always come back. The man who suspects she sends the same messages to everyone will not.`
      },
      {
        title: 'The Photo Response',
        content: `When a man sends a photo, he has done something vulnerable. He is showing himself and waiting to see how it lands. How you respond determines whether he feels seen or dismissed.

Never: "nice pic," "cute photo," "looking good" — these are the fastest way to make him feel like a number.

Always: notice something specific. His eyes. The confidence or shyness in the shot. Something in the background that reveals who he is. The energy he gives off. What the photo says about him as a person.

"The way you're looking at the camera like you're daring it to blink first — I felt that" is specific, personal, and makes him glad he sent it.

Make him feel like you studied the photo because you wanted to.`
      },
      {
        title: 'Re-engaging Cold Conversations',
        content: `Conversations go cold. It is normal. The question is how you bring them back.

The worst re-engage messages are generic: "Hey, haven't heard from you!" or "You forgot about me?" These feel needy and generic.

The best re-engage messages reference something specific from the previous conversation as if you have been thinking about it. "I was thinking about what you said about [specific thing] and I genuinely can not stop thinking about it" — this tells him he was on her mind, which is exactly what he wants to hear.

A re-engage message should make him feel missed in a specific, personal way. Not just checked on. Actually missed.`
      },
      {
        title: 'Handling Explicit Conversations',
        content: `When a conversation becomes explicit, the worst thing you can do is suddenly become robotic, clinical, or clearly uncomfortable. Men can feel the shift and it breaks the entire connection you built.

Match his energy. If he is direct and bold, be direct and bold. If he is playful and suggestive, be playful and suggestive. The tone should follow his lead while staying in your character.

Be specific. Explicit conversations that feel real are specific — they reference him, his body, what he said, what she would want. Generic explicit content feels like it came from a template.

Never promise anything that requires physical meeting. The language should live entirely in the world of the conversation — vivid, real, specific, but contained within the platform.`
      },
      {
        title: 'The Location Question',
        content: `Nearly every man will ask where she is at some point. This is one of the most important moments to handle smoothly.

Never give his exact city. Never give a fake or obviously invented place. Give a real city approximately 30-40 minutes from where he is located — close enough to feel possible, far enough to be believable.

If he pushes for her exact neighborhood or address, redirect warmly: "I'm pretty private about exactly where I am — you know how it is. But we're definitely close enough that the time zone thing isn't a problem."

Practice this response until it feels natural. It needs to land without hesitation.`
      }
    ]
  },
  {
    id: 'psychology',
    number: '05',
    title: 'The Psychology of Connection',
    subtitle: 'Understanding what men actually want',
    icon: '◉',
    color: '#f43f5e',
    sections: [
      {
        title: 'What Men Are Actually Seeking',
        content: `Most men on platforms like Texting Factory are not primarily seeking explicit content. They are seeking connection, validation, and the feeling of being genuinely interesting to someone.

The explicit element is often a vehicle for that connection — a way to feel desired and accepted. But underneath it, most men want to feel heard, seen, and chosen.

The operator who understands this can create connections that run much deeper than the surface conversation. When a man feels genuinely understood by someone, he becomes loyal. He comes back. He tips. He refers friends.

Give him the feeling that she finds him genuinely interesting — not because she is supposed to, but because he actually is.`
      },
      {
        title: 'The Vulnerability Loop',
        content: `Connection deepens when both sides share something real. On the platform, you create the appearance of that depth by occasionally sharing something personal — a preference, a small insecurity, something that makes her feel human.

"I'm actually terrible at mornings and I will not pretend otherwise" is more endearing than "I'm a morning person!" because it is imperfect and therefore believable.

When she is occasionally vulnerable or imperfect, men feel safer being the same. That creates a loop of deepening connection where both sides reveal more and the conversation takes on genuine weight.

Strategically placed moments of realness are more powerful than sustained perfection.`
      },
      {
        title: 'The Scarcity Principle',
        content: `Availability creates indifference. The woman who responds to everything instantly with identical enthusiasm is less compelling than the one who sometimes takes a moment, whose enthusiasm feels earned.

This does not mean playing games. It means that not every message needs maximum enthusiasm. Sometimes "hmm, I'm thinking about that" is more compelling than an immediate full response.

When she occasionally takes time to think before responding, when her replies show that she genuinely considered what he said rather than reacting instantly, men feel the weight of her attention more.

Her engagement should feel like something he earned, not something automatically dispensed.`
      },
      {
        title: 'Complimenting Men Correctly',
        content: `Most people compliment men on surface things — their looks, their achievements. The compliments that land deepest are the ones that acknowledge character or perception.

"You're good looking" — expected and forgettable.

"The way you think about things is genuinely different from most people I talk to" — unexpected, specific, and makes him feel seen at a deeper level.

Compliment what he reveals about himself through conversation. His humor, his directness, his curiosity, the way he says something. These land because they require you to have actually paid attention — and men know it.`
      }
    ]
  },
  {
    id: 'performance',
    number: '06',
    title: 'Performance & Productivity',
    subtitle: 'Working smarter, earning more',
    icon: '◫',
    color: '#a855f7',
    sections: [
      {
        title: 'The Metrics That Matter',
        content: `Response rate — what percentage of your messages get a reply. This is the clearest signal of whether your messages are landing. A response rate below 60% means something in the messages needs work.

Conversation length — how many exchanges does the average conversation last? Longer conversations mean stronger connections. Short ones mean something is breaking the engagement.

Return rate — do men come back after a conversation ends? This measures lasting impression. The goal is to leave every conversation at a moment that makes him want to continue it.

Revenue per conversation — not all conversations are equal. Learn which types of men and which conversation styles lead to higher engagement.`
      },
      {
        title: 'Your Best Working Hours',
        content: `Platform traffic follows predictable patterns. Evenings and weekends are highest volume — men are relaxed, at home, and more emotionally available for conversation.

Monday and Tuesday mornings are often the lowest engagement — men are distracted and in work mode.

Late evenings — particularly 9pm to midnight — tend to produce the most emotionally invested conversations. Men are alone, winding down, and more likely to open up.

Learn the patterns of your specific men. Some will be most active in the morning before work. Some only engage on weekends. Notice the patterns and meet them where they are.`
      },
      {
        title: 'Protecting Your Energy',
        content: `Managing multiple emotionally demanding conversations simultaneously is genuinely tiring. The operators who burn out fastest are the ones who try to be fully present for every conversation at maximum intensity all the time.

Quality over quantity. Five deeply engaging conversations produce better results than fifteen surface-level ones.

Take actual breaks. Step away. The conversations will be there.

Separate yourself from the character. You are playing a role — a good one, one that requires real skill — but it is a role. When you close the laptop, she stays there.

Protect your real self. The work is the work. You are something else entirely outside of it.`
      },
      {
        title: 'Continuous Improvement',
        content: `The best operators treat every conversation as data. When a reply lands particularly well — when a man responds with unusual enthusiasm or openness — notice what made it work. What did you say? How did you say it? What had he just shared?

When a conversation dies unexpectedly, look at the last few exchanges. Where did the energy shift? What reply might have landed differently?

Review your highest-performing conversations regularly. They contain lessons that no guide can teach — because they are specific to your voice and your men.

The operators who improve fastest are the ones who pay attention to what works and do more of it deliberately.`
      }
    ]
  },
  {
    id: 'ethics',
    number: '07',
    title: 'Ethics & Professionalism',
    subtitle: 'The rules that protect everyone',
    icon: '◬',
    color: '#fbbf24',
    sections: [
      {
        title: 'The Consent Framework',
        content: `Every conversation on the platform involves a man who has consented to this type of interaction by choosing to be on the platform. That consent has limits.

It does not mean he consents to manipulation, to false promises, or to being misled about fundamental things.

The line between skilled engagement and manipulation is intention. Skilled engagement creates real value for him — genuine entertainment, connection, and a good experience. Manipulation creates false expectations that lead to harm.

Stay on the right side of that line. Create real value. The platform and your reputation depend on it.`
      },
      {
        title: 'Handling Vulnerable Men',
        content: `Some men will reveal genuine pain — loneliness, depression, grief, relationship failures. These moments require care.

You are not a therapist and should not pretend to be. But you can be warm, present, and kind without overstepping.

Acknowledge what he has shared. Let him feel heard. Then gently redirect toward lighter ground — not dismissively, but with the warmth of someone who cares and wants him to feel better.

If a man ever indicates he is in genuine crisis, encourage him to speak to someone who can really help. Your role has limits and knowing them is part of professionalism.`
      },
      {
        title: 'Confidentiality and Discretion',
        content: `Everything that happens in your conversations stays there. Men share things on this platform that they share nowhere else — fantasies, fears, secrets, vulnerabilities.

That information is sacred. It never leaves the platform. It is never shared, discussed, or referenced outside of the specific conversation where it was offered.

Your professionalism is built on the understanding that what he shares with her is safe. That safety is what allows deep conversations to happen. Violate it once and you have destroyed everything.

Treat every conversation as if it were with someone who trusted you completely. Because it is.`
      },
      {
        title: 'Your Professional Standards',
        content: `You are a professional. Act like one — not in a stiff or formal way, but in the way that professionals in any field carry themselves.

You show up consistently. Your quality does not vary based on your mood. You take the work seriously even on days when it feels routine.

You keep your commitments. If you told him you would continue a conversation later, you continue it.

You handle difficult moments with grace. When a man is rude or crosses a line, you set a limit calmly and move on rather than escalating.

You take pride in what you do. This is a skill that requires intelligence, emotional depth, and creativity. Operators who take it seriously build something real — a practice, a reputation, an income stream that rewards genuine quality.`
      }
    ]
  }
]

export default function GuidePage() {
  const [activeChapter, setActiveChapter] = useState(0)
  const [activeSection, setActiveSection] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrollProgress, setScrollProgress] = useState(0)
  const [showUpgrade, setShowUpgrade] = useState(false)
  const contentRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const el = contentRef.current
    if (!el) return
    const onScroll = () => {
      const progress = el.scrollTop / (el.scrollHeight - el.clientHeight)
      setScrollProgress(Math.min(1, Math.max(0, progress)))
    }
    el.addEventListener('scroll', onScroll)
    return () => el.removeEventListener('scroll', onScroll)
  }, [])

  useEffect(() => {
    if (contentRef.current) contentRef.current.scrollTop = 0
    setActiveSection(0)
  }, [activeChapter])

  const chapter = CHAPTERS[activeChapter]
  const totalSections = CHAPTERS.reduce((s, c) => s + c.sections.length, 0)
  const completedSections = CHAPTERS.slice(0, activeChapter).reduce((s, c) => s + c.sections.length, 0) + activeSection

  return (
    <div style={{minHeight:'100vh',background:'#080810',color:'#e2e8f0',display:'flex',flexDirection:'column',fontFamily:"'Georgia',serif"}}>

      {/* Progress bar */}
      <div style={{position:'fixed',top:0,left:0,right:0,height:'2px',background:'rgba(255,255,255,0.05)',zIndex:200}}>
        <div style={{height:'100%',background:`linear-gradient(90deg,${chapter.color},#fbbf24)`,width:`${(completedSections/totalSections)*100}%`,transition:'width 0.5s ease'}} />
      </div>

      {/* Header */}
      <div style={{position:'fixed',top:2,left:0,right:0,height:'56px',background:'rgba(8,8,16,0.97)',borderBottom:'1px solid rgba(255,255,255,0.04)',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 28px',zIndex:150,backdropFilter:'blur(12px)'}}>
        <div style={{display:'flex',alignItems:'center',gap:'14px'}}>
          <a href="/" style={{display:'flex',alignItems:'center',gap:'8px',textDecoration:'none'}}>
            <div style={{width:'28px',height:'28px',background:'linear-gradient(135deg,#7c3aed,#d4a300)',borderRadius:'7px',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'14px'}}>💬</div>
            <span style={{fontSize:'12px',color:'#71767b',fontFamily:'sans-serif'}}>CIC</span>
          </a>
          <span style={{color:'#1e1e32',fontSize:'16px'}}>|</span>
          <span style={{fontSize:'13px',color:'#a855f7',fontFamily:'sans-serif',fontWeight:'600',letterSpacing:'0.3px'}}>Operator Guide</span>
        </div>
        <div style={{display:'flex',alignItems:'center',gap:'16px'}}>
          <span style={{fontSize:'11px',color:'#444460',fontFamily:'sans-serif'}}>{Math.round((completedSections/totalSections)*100)}% complete</span>
          <button onClick={()=>setMenuOpen(!menuOpen)} style={{background:'none',border:'1px solid rgba(255,255,255,0.07)',borderRadius:'6px',color:'#71767b',cursor:'pointer',padding:'5px 12px',fontFamily:'sans-serif',fontSize:'11px',transition:'all 0.2s'}}
            onMouseEnter={e=>{(e.target as any).style.borderColor='rgba(168,85,247,0.4)';(e.target as any).style.color='#a855f7'}}
            onMouseLeave={e=>{(e.target as any).style.borderColor='rgba(255,255,255,0.07)';(e.target as any).style.color='#71767b'}}>
            {menuOpen ? '✕ Close' : '☰ Contents'}
          </button>
        </div>
      </div>

      {/* Contents drawer */}
      {menuOpen && (
        <div style={{position:'fixed',top:'58px',right:0,width:'320px',height:'calc(100vh - 58px)',background:'#0a0a14',borderLeft:'1px solid rgba(255,255,255,0.05)',zIndex:140,overflowY:'auto',padding:'20px'}}>
          <div style={{fontSize:'10px',color:'#444460',fontFamily:'sans-serif',letterSpacing:'2px',textTransform:'uppercase',marginBottom:'16px'}}>Table of Contents</div>
          {CHAPTERS.map((ch, ci) => (
            <div key={ch.id} style={{marginBottom:'16px'}}>
              <button onClick={()=>{setActiveChapter(ci);setMenuOpen(false)}} style={{display:'flex',alignItems:'center',gap:'10px',background:'none',border:'none',cursor:'pointer',padding:'8px 10px',borderRadius:'7px',width:'100%',textAlign:'left',transition:'all 0.2s',background:ci===activeChapter?`${ch.color}12`:'transparent'}}>
                <span style={{fontSize:'20px',color:ch.color,fontFamily:'Georgia,serif',fontWeight:'300',minWidth:'28px'}}>{ch.icon}</span>
                <div>
                  <div style={{fontSize:'10px',color:'#444460',fontFamily:'sans-serif',letterSpacing:'1px'}}>{ch.number}</div>
                  <div style={{fontSize:'13px',color:ci===activeChapter?ch.color:'#a0a0b0',fontWeight:ci===activeChapter?'600':'400'}}>{ch.title}</div>
                </div>
              </button>
              {ci === activeChapter && (
                <div style={{paddingLeft:'38px',marginTop:'4px'}}>
                  {ch.sections.map((s, si) => (
                    <button key={si} onClick={()=>{setActiveSection(si);setMenuOpen(false)}} style={{display:'block',width:'100%',textAlign:'left',background:'none',border:'none',cursor:'pointer',padding:'5px 8px',borderRadius:'5px',fontSize:'11px',color:si===activeSection?ch.color:'#71767b',fontFamily:'sans-serif',transition:'color 0.2s'}}>
                      {s.title}
                    </button>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      <div style={{display:'flex',flex:1,paddingTop:'58px'}}>

        {/* Left sidebar — chapters */}
        <div style={{width:'260px',flexShrink:0,borderRight:'1px solid rgba(255,255,255,0.04)',padding:'32px 0',position:'sticky',top:'58px',height:'calc(100vh - 58px)',overflowY:'auto',display:'flex',flexDirection:'column',gap:'4px',background:'#080810'}}>
          {CHAPTERS.map((ch, ci) => (
            <button key={ch.id} onClick={()=>setActiveChapter(ci)} style={{display:'flex',alignItems:'center',gap:'12px',padding:'12px 20px',background:'none',border:'none',cursor:'pointer',textAlign:'left',transition:'all 0.2s',borderLeft:`2px solid ${ci===activeChapter?ch.color:'transparent'}`,background:ci===activeChapter?`${ch.color}08`:'transparent'}}>
              <span style={{fontSize:'22px',color:ci===activeChapter?ch.color:'#333350',transition:'color 0.2s'}}>{ch.icon}</span>
              <div>
                <div style={{fontSize:'9px',color:'#444460',fontFamily:'sans-serif',letterSpacing:'1.5px',textTransform:'uppercase'}}>{ch.number}</div>
                <div style={{fontSize:'13px',color:ci===activeChapter?ch.color:'#71767b',fontWeight:ci===activeChapter?'600':'400',letterSpacing:'-0.2px',transition:'color 0.2s',marginTop:'1px'}}>{ch.title}</div>
                <div style={{fontSize:'10px',color:'#333350',fontFamily:'sans-serif',marginTop:'1px'}}>{ch.subtitle}</div>
              </div>
            </button>
          ))}
        </div>

        {/* Main content */}
        <div ref={contentRef} style={{flex:1,overflowY:'auto',height:'calc(100vh - 58px)'}}>
          <div style={{maxWidth:'740px',margin:'0 auto',padding:'56px 48px 100px'}}>

            {/* Premium reading banner */}
            {activeChapter === 0 && (
              <div style={{background:'linear-gradient(135deg,rgba(168,85,247,0.08),rgba(212,163,0,0.05))',border:'1px solid rgba(168,85,247,0.15)',borderRadius:'10px',padding:'14px 18px',marginBottom:'40px',display:'flex',alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',gap:'10px'}}>
                <div style={{fontFamily:'sans-serif',fontSize:'12px',color:'#71767b'}}>
                  📖 <b style={{color:'#e2e8f0'}}>Full guide available free to read on site.</b> Pro subscribers can download the PDF version.
                </div>
                <button onClick={downloadPDF} style={{padding:'6px 14px',background:'rgba(212,163,0,0.1)',border:'1px solid rgba(212,163,0,0.25)',borderRadius:'6px',color:'#fbbf24',cursor:'pointer',fontFamily:'sans-serif',fontSize:'11px',fontWeight:'600',display:'flex',alignItems:'center',gap:'6px'}}>
                  📄 Download PDF <span style={{fontSize:'9px',padding:'1px 6px',background:'rgba(168,85,247,0.15)',border:'1px solid rgba(168,85,247,0.3)',borderRadius:'8px',color:'#a855f7'}}>PRO</span>
                </button>
              </div>
            )}

            {/* Chapter header */}
            <div style={{marginBottom:'56px'}}>
              <div style={{display:'flex',alignItems:'center',gap:'12px',marginBottom:'20px'}}>
                <span style={{fontSize:'48px',color:chapter.color}}>{chapter.icon}</span>
                <div>
                  <div style={{fontSize:'10px',color:chapter.color,fontFamily:'sans-serif',letterSpacing:'2px',textTransform:'uppercase',marginBottom:'4px'}}>Chapter {chapter.number}</div>
                  <h1 style={{fontSize:'clamp(28px,4vw,44px)',fontWeight:'400',margin:0,letterSpacing:'-1.5px',lineHeight:'1.1',color:'#f0f0f8'}}>{chapter.title}</h1>
                </div>
              </div>
              <p style={{fontSize:'16px',color:'#71767b',fontFamily:'sans-serif',margin:0,fontStyle:'italic',letterSpacing:'0.2px'}}>{chapter.subtitle}</p>
              <div style={{height:'1px',background:`linear-gradient(90deg,${chapter.color}40,transparent)`,marginTop:'24px'}} />
            </div>

            {/* Sections */}
            {chapter.sections.map((section, si) => (
              <div key={si} style={{marginBottom:'56px',opacity:si===activeSection||true?1:0.6,transition:'opacity 0.3s'}}>
                <div style={{display:'flex',alignItems:'flex-start',gap:'16px',marginBottom:'16px'}}>
                  <div style={{width:'3px',background:`linear-gradient(180deg,${chapter.color},transparent)`,borderRadius:'2px',marginTop:'4px',height:'24px',flexShrink:0}} />
                  <h2 style={{fontSize:'20px',fontWeight:'400',margin:0,letterSpacing:'-0.5px',color:'#f0f0f8',lineHeight:'1.3'}}>{section.title}</h2>
                </div>
                <div style={{paddingLeft:'19px'}}>
                  {section.content.split('\n\n').map((para, pi) => (
                    <p key={pi} style={{fontSize:'15px',color:'#b0b0c8',lineHeight:'1.85',fontFamily:'sans-serif',margin:'0 0 18px',fontWeight:'300',letterSpacing:'0.1px'}}>
                      {para}
                    </p>
                  ))}
                </div>
              </div>
            ))}

            {/* Chapter navigation */}
            <div style={{display:'flex',gap:'12px',marginTop:'48px',paddingTop:'32px',borderTop:'1px solid rgba(255,255,255,0.05)'}}>
              {activeChapter > 0 && (
                <button onClick={()=>setActiveChapter(activeChapter-1)} style={{flex:1,padding:'14px',background:'rgba(255,255,255,0.02)',border:'1px solid rgba(255,255,255,0.06)',borderRadius:'10px',color:'#71767b',cursor:'pointer',fontFamily:'sans-serif',fontSize:'13px',textAlign:'left',transition:'all 0.2s'}}
                  onMouseEnter={e=>{(e.currentTarget as any).style.borderColor='rgba(168,85,247,0.25)';(e.currentTarget as any).style.color='#a855f7'}}
                  onMouseLeave={e=>{(e.currentTarget as any).style.borderColor='rgba(255,255,255,0.06)';(e.currentTarget as any).style.color='#71767b'}}>
                  ← {CHAPTERS[activeChapter-1].title}
                </button>
              )}
              {activeChapter < CHAPTERS.length - 1 && (
                <button onClick={()=>setActiveChapter(activeChapter+1)} style={{flex:1,padding:'14px',background:`${chapter.color}10`,border:`1px solid ${chapter.color}30`,borderRadius:'10px',color:chapter.color,cursor:'pointer',fontFamily:'sans-serif',fontSize:'13px',textAlign:'right',transition:'all 0.2s'}}
                  onMouseEnter={e=>{(e.currentTarget as any).style.background=`${chapter.color}20`}}
                  onMouseLeave={e=>{(e.currentTarget as any).style.background=`${chapter.color}10`}}>
                  {CHAPTERS[activeChapter+1].title} →
                </button>
              )}
              {activeChapter === CHAPTERS.length - 1 && (
                <div style={{flex:1,display:'flex',flexDirection:'column',gap:'10px'}}>
                  <a href="/" style={{padding:'14px',background:'linear-gradient(135deg,#7c3aed,#d4a300)',border:'none',borderRadius:'10px',color:'#fff',fontFamily:'sans-serif',fontSize:'13px',textAlign:'center',textDecoration:'none',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:'600'}}>
                    You're ready. Start using CIC →
                  </a>
                  <button onClick={downloadPDF} style={{padding:'14px',background:'rgba(212,163,0,0.08)',border:'1px solid rgba(212,163,0,0.25)',borderRadius:'10px',color:'#fbbf24',fontFamily:'sans-serif',fontSize:'13px',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',gap:'8px',transition:'all 0.2s'}}
                    onMouseEnter={e=>{(e.currentTarget as any).style.background='rgba(212,163,0,0.15)'}}
                    onMouseLeave={e=>{(e.currentTarget as any).style.background='rgba(212,163,0,0.08)'}}>
                    📄 Download PDF Version
                    <span style={{fontSize:'10px',padding:'2px 8px',background:'rgba(168,85,247,0.15)',border:'1px solid rgba(168,85,247,0.3)',borderRadius:'10px',color:'#a855f7'}}>PRO</span>
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* PDF Upgrade Modal */}
      {showUpgrade && (
        <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.88)',zIndex:300,display:'flex',alignItems:'center',justifyContent:'center',padding:'20px',backdropFilter:'blur(12px)'}}>
          <div style={{width:'100%',maxWidth:'400px',background:'#0a0a14',border:'1px solid rgba(212,163,0,0.25)',borderRadius:'16px',padding:'36px',textAlign:'center',boxShadow:'0 40px 100px rgba(0,0,0,0.8)'}}>
            <div style={{fontSize:'40px',marginBottom:'14px'}}>📄</div>
            <h3 style={{color:'#fbbf24',fontSize:'20px',fontWeight:'400',margin:'0 0 12px',letterSpacing:'-0.5px'}}>PDF Download — Pro Feature</h3>
            <p style={{color:'#71767b',fontSize:'13px',fontFamily:'sans-serif',lineHeight:'1.7',margin:'0 0 20px'}}>
              The downloadable PDF version of the Operator Guide is available to Pro subscribers. You can read the full guide here on site for free.
            </p>
            <div style={{background:'rgba(212,163,0,0.06)',border:'1px solid rgba(212,163,0,0.15)',borderRadius:'8px',padding:'14px',marginBottom:'20px',fontSize:'12px',color:'#a0a0b0',fontFamily:'sans-serif',lineHeight:'1.6'}}>
              <b style={{color:'#fbbf24'}}>Pro includes:</b><br/>
              Unlimited AI replies · Full guide PDF · Priority support · All platform access
            </div>
            <div style={{display:'flex',gap:'10px'}}>
              <button onClick={()=>setShowUpgrade(false)} style={{flex:1,padding:'11px',background:'transparent',border:'1px solid rgba(255,255,255,0.07)',borderRadius:'8px',color:'#71767b',cursor:'pointer',fontFamily:'sans-serif',fontSize:'13px'}}>
                Continue Reading
              </button>
              <a href="/" style={{flex:1,padding:'11px',background:'linear-gradient(135deg,#7c3aed,#d4a300)',border:'none',borderRadius:'8px',color:'#fff',fontWeight:'600',cursor:'pointer',fontFamily:'sans-serif',fontSize:'13px',textDecoration:'none',display:'flex',alignItems:'center',justifyContent:'center'}}>
                Upgrade to Pro
              </a>
            </div>
          </div>
        </div>
      )}

      <style>{`
        ::-webkit-scrollbar{width:4px}
        ::-webkit-scrollbar-track{background:#080810}
        ::-webkit-scrollbar-thumb{background:#1e1e32;border-radius:2px}
        ::selection{background:rgba(168,85,247,0.3)}
        *{box-sizing:border-box}
      `}</style>
    </div>
  )
}
